Gym_Website/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from gym_website_app.views import index, signup_login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', index, name='index'),
    path('gym_website_app/', include('gym_website_app.urls', 'gym_website_app')),
    path('blog_app/', include('blog_app.urls', 'blog_app')),
    path('login/', signup_login, name='login'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_app/urls.py
from django.urls import path, re_path
from .views import profile, PostListView, PostDetailView, PostCreateView,\
    PostUpdateView, PostDeleteView, UserPostListView, UserProfileView
from gym_website_app.views import signup_login


app_name = 'blog_app'

urlpatterns = [
    re_path(r'^$', PostListView.as_view(), name='blog_index'),
    path('index/', PostListView.as_view(), name='blog_index'),
    path('user_posts/<str:username>/', UserPostListView.as_view(), name='user_posts'),
    path('post_detail/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post/new/', PostCreateView.as_view(), name='post_create'),
    path('post_detail/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('post_detail/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('login/', signup_login, name='login'),
    path('profile/', UserProfileView.as_view(), name='profile'),
]

gym_website_app/urls.py
from django.urls import path, re_path
from .views import index, signup_login, validate_username, user_logout

app_name = 'gym_website_app'

urlpatterns = [
    re_path(r'^$', index, name='home'),
    path('index/', index, name='index'),
    path('signup_login/', signup_login, name='signup & login'),
    path('login/', signup_login, name='login'),
    path('validate_uname', validate_username, name='validate_uname'),
    path('logout/', user_logout, name='logout user')
]

blog_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.urls import reverse
from PIL import Image

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=100)
    date_posted = models.DateTimeField(default=timezone.now)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def get_absolute_url(self):
        return reverse('blog_app:post_detail', kwargs={'pk': self.pk})


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics', default='default.jpg')

    def __str__(self):
        return f"{self.user.username}'s Profile"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.profile_pic.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.profile_pic.path)


def create_profile(sender, **kwargs):
    if kwargs['created']:
        profile = Profile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)

gym_website_app/models.py
from django.db import models

# Create your models here.

gym_website_app/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User

blog_app/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Post
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

# Create your views here.


@login_required
def blog_index(request):
    context_dict = {'posts': Post.objects.all()}
    response = render(request, 'blog_app/blog_index.html', context_dict)
    return response


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog_app/blog_index.html'
    ordering = ['-date_posted']
    context_object_name = 'posts'
    paginate_by = 6


class UserPostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog_app/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 6

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/blog_app/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


@login_required
def profile(request):
    context_dict = {}
    response = render(request, 'blog_app/profile.html', context_dict)
    return response


class UserProfileView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog_app/profile.html'
    context_object_name = 'posts'
    paginate_by = 6

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user).order_by('-date_posted')

gym_website_app/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.


def index(request):
    context_dict = {}
    response = render(request, 'index.html', context_dict)
    return response


def signup_login(request):
    context_dict = {}
    if request.method == 'GET':
        pass
    else:
        user_data = request.POST
        username = user_data.get('username')
        email = user_data.get('email')
        password = user_data.get('password')

        # Signup handling goes here

        if user_data.get('submit') == 'signup':
            data = {
                'user_created': False
            }
            try:
                User.objects.create_user(username=username, email=email, password=password)
            except Exception as e:
                print(f'exception is {e}')
                return JsonResponse(data)
            else:
                data['user_created'] = True
                messages.success(request, f"User created successfully for '{username}'")
                return JsonResponse(data)

        # LOGIN handling

        elif user_data.get('submit') == 'login':
            user = authenticate(username=username, password=password)
            next_url = user_data.get('next')          # next_url gives the url to redirect to previous page after login
            print("next in post: {}".format(next_url))
            if user:
                login(request, user)
                return JsonResponse({'logged_in': True, 'next_url': next_url})
            else:
                print("Authentication failed")
                return JsonResponse({'logged_in': False})

        else:
            print("in no where")
            pass

    response = render(request, 'signup.html', context_dict)
    return response


def validate_username(request):
    username = request.GET.get('username')
    print(username)
    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    if data['is_taken']:
        data['message'] = 'already taken!'
    else:
        data['message'] = 'available'
    return JsonResponse(data)


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

templates/blog_app/blog_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static "blog_app/css/main.css" %}">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>

    <header class="site-header">
          <nav style="background-color: #0c0100" class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
              <a class="navbar-brand mr-4" href="{% url 'blog_app:blog_index' %}">Alif Blog</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                  <a class="nav-item nav-link" href="{% url 'blog_app:blog_index' %}">Home</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                  <a class="nav-item nav-link" href="{% url 'blog_app:post_create' %}">New Post</a>
                  <a class="nav-item nav-link" href="{% url 'blog_app:profile' %}">Profile</a>
                  <a class="nav-item nav-link" href="{% url 'gym_website_app:logout user' %}">Logout</a>
{#                  <a class="nav-item nav-link" href="#">Register</a>#}
                </div>
              </div>
            </div>
          </nav>
    </header>



    <main role="main" class="container">
          <div class="row">
            <div class="col-md-8">
              {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
              <div class="content-section">
                <h3>Our Sidebar</h3>
                <p class='text-muted'>You can put any information here you'd like.</p>
                  <ul class="list-group">
                    <li class="list-group-item list-group-item-light">Latest Posts</li>
                    <li class="list-group-item list-group-item-light">Announcements</li>
                    <li class="list-group-item list-group-item-light">Calendars</li>
                    <li class="list-group-item list-group-item-light">etc</li>
                  </ul>

              </div>
            </div>
          </div>
    </main>



<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/blog_app/blog_index.html
{% extends 'blog_app/blog_base.html' %}

{% block title %}Blog Home{% endblock %}

{% block content %}
    {% for post in posts %}
    <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.author.profile.profile_pic.url }}" alt="Missing Profile Pic">
          <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="{% url 'blog_app:user_posts' post.author.username %}">{{ post.author }}</a>
                  <small class="text-muted">{{ post.date_posted|date:'F d, Y' }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'blog_app:post_detail' post.id %}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
          </div>
    </article>
    {% endfor %}

    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Prev</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages}}">Last</a>
        {% endif %}

    {% endif %}

{% endblock content %}

templates/blog_app/post_detail.html
{% extends 'blog_app/blog_base.html' %}

{% block title %}Detail| {{ object.title }}{% endblock %}

{% block content %}
    <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ object.author.profile.profile_pic.url }}" alt="Author's Image">
          <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="{% url 'blog_app:user_posts' object.author.username %}">{{ object.author }}</a>
                  <small class="text-muted">{{ object.date_posted|date:'F d, Y' }}</small>

                    {% if object.author == user %}
                      <div>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog_app:post_delete' object.pk %}">Delete</a>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blog_app:post_update' object.pk %}">Update</a>
                      </div>
                  {% endif %}
                </div>
                <h2 class="article-title">{{ object.title }}</h2>
                <p class="article-content">{{ object.content }}</p>
          </div>
    </article>
{% endblock content %}

templates/blog_app/post_form.html
{% extends 'blog_app/blog_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Post| Create {% endblock %}

{% block content %}
    <div class="content-section">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                    {#  object.pk == True means we are in PostUpdate view, else we are in PostCreate view   #}
                <button class="btn btn-outline-info" type="submit">{% if object.pk %}
                                                                            Update
                                                                    {% else %}
                                                                            Post
                                                                    {% endif %}</button>
                <a class="btn btn-outline-secondary float-right" href="{% if object.pk %}
                                                                                {% url 'blog_app:post_detail' object.pk %}
                                                                        {% else %}
                                                                                {% url 'blog_app:blog_index' %}
                                                                        {% endif %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

templates/blog_app/profile.html
{% extends 'blog_app/blog_base.html' %}

{% block title%}{{ user.username }}| Profile{% endblock %}

{% block content %}
<div class="content-section">
  <div class="media">
    <img class="rounded-circle account-img" src="{{ user.profile.profile_pic.url }}">
    <div class="media-body">
      <h2 class="account-heading">{{ user.username }}</h2>
      <p class="text-secondary">{{ user.email }}</p>
    </div>
  </div>
  <!-- FORM HERE -->
</div>

    <h1 class="text-white mb-3">Your Posts ({{ page_obj.paginator.count }})</h1>
    {% for post in posts %}
    <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.author.profile.profile_pic.url }}" alt="Missing Profile Pic">
          <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="{% url 'blog_app:user_posts' post.author.username %}">{{ post.author }}</a>
                  <small class="text-muted">{{ post.date_posted|date:'F d, Y' }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'blog_app:post_detail' post.id %}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
          </div>
    </article>
    {% endfor %}

    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Prev</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages}}">Last</a>
        {% endif %}

    {% endif %}

{% endblock content %}

templates/blog_app/user_posts.html
{% extends 'blog_app/blog_base.html' %}

{% block title %}Posts| {{ view.kwargs.username }}{% endblock %}

{% block content %}
    <h1 class="text-white mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for post in posts %}
    <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.author.profile.profile_pic.url }}" alt="Missing Profile Pic">
          <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="{% url 'blog_app:user_posts' post.author.username %}">{{ post.author }}</a>
                  <small class="text-muted">{{ post.date_posted|date:'F d, Y' }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'blog_app:post_detail' post.id %}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
          </div>
    </article>
    {% endfor %}

    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Prev</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages}}">Last</a>
        {% endif %}

    {% endif %}

{% endblock content %}

templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en-us">

<head>
    <title>Register</title>
    <link href="{% static 'css/signup.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="{% static 'js/signup.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
</head>

<script type="text/javascript">
    $(document).ready(function () {
        console.log("Page loaded");
        let login_form = $('#js-login-form');
        let signup_form = $('#js-signup-form');
        let signup_uname_field = $('#js-signup-username');
        let signup_uname_validation = $('#js-signup-username-validation');
        let signup_email_field = $('#js-signup-email');
        let signup_password_field = $('#js-signup-password');
        let signup_con_pass_field = $('#js-signup-confirm-password');
        let signup_con_pass_validation = $('#js-signup-con-pass-validation');
        let signup_button = $('#js-signup-button');
        let login_validation_field = $('#js-login-validation');

        {#   Hide confirm password field#}
        signup_con_pass_field.hide(0);

        {#   Clear confirm-password-validation field#}
        signup_con_pass_field.keyup(function () {
           signup_con_pass_validation.html('');
        });

        {#   Show confirm password field#}
        signup_password_field.keyup(function () {
           let val = $(this).val();
           let n = 0;
           if(val === ''){
               signup_con_pass_field.hide(400);
           }
           if(val !== '' && n === 0){           {# only runs when n = 0, so it does not run with every keyup trigger #}
               signup_con_pass_field.show(400);
               n = 1;
            }
        });


        {#       username validation              #}

        signup_uname_field.keyup(function () {
            signup_uname_validation.html('');
            console.log("Key pressed uname");
            let username = $(this).val();
            if (username !== ''){
                let form = signup_uname_field.closest('form');
                $.ajax({
                    url: '{% url 'gym_website_app:validate_uname' %}',
                    data: form.serialize(),
                    dataType: 'json',
                    success: function (data) {
                        if(data.is_taken){
                            signup_uname_validation.html(username+" "+data.message);
                            signup_uname_validation.css('color', 'red');
                            signup_button.hide(500);

                        }
                        else{
                            signup_uname_validation.html(username+" is "+data.message);
                            signup_uname_validation.css('color', 'green');
                            signup_button.show(400);
                        }
                    }
                })
            }
        });

        {#         Signup Form Validation   #}

        signup_form.submit(function (e) {
            e.preventDefault();
            let username = signup_uname_field.val();
            let password = signup_password_field.val();
            if(username !== '' && password !== ''){
                if (signup_password_field.val() === signup_con_pass_field.val()){    {# ao form does not gets submitted empty #}
                    $.ajax({
                        url: '{% url 'gym_website_app:signup & login' %}',
                        type: 'POST',
                        data: {
                            csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").attr('value'),
                            username: username,
                            password: password,
                            email: signup_email_field.val(),
                            submit: 'signup',
                                },
                        dataType: 'json',
                        success: function (data) {
                            if (data.user_created){
                                {#signup_form.find("input[type=text], textarea").val('');#}
                                {#signup_con_pass_validation.css('color', 'green');#}
                                {#signup_con_pass_validation.html("User created successfully!");#}
                                window.location.href = '{% url 'gym_website_app:signup & login' %}'
                            }
                            else {
                                signup_con_pass_validation.css('color', 'red');
                                signup_con_pass_validation.html("User creation failed! Try again!");
                            }
                        }
                    })
                }
                else {

                    signup_con_pass_validation.css('color', 'red');
                    signup_con_pass_validation.html("Passwords do not match");
                }
             }
            else{
                signup_con_pass_validation.css('color', 'red');
                    signup_con_pass_validation.html("Username/password field is empty!");
             }
         });


        {#       LOGIN VALIDATION FORM   #}

        login_form.submit(function (e) {
            e.preventDefault();
            let username = $('#js-login-username').val();
            let password = $('#js-login-password').val();
            let next = $('#js-login-next').val()
            if(username !== '' && password!== ''){                    {# so form doen not gets submitted empty #}
                $.ajax({
                    url: '{% url 'gym_website_app:signup & login' %}',
                    data: {
                        username: username,
                        password: password,
                        next: next,
                        csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").attr('value'),
                        submit: 'login',
                    },
                    type: 'POST',
                    dataType: 'json',
                    success: function (data) {
                        if(data.logged_in){
                            if (data.next_url){
                                console.log(data.next_url);
                                console.log(data.next_url.toString());
                                window.location.href = data.next_url
                            }
                            else{
                                window.location.href = "{% url 'blog_app:blog_index' %}"
                            }
                        }
                        else {
                            login_validation_field.html("username/password is invalid!");

                            {#   Error message would disappear when form is clicked#}
                            login_form.click(function () {
                                login_validation_field.html('')
                            })
                        }
                    }
                })
            }
            else{
                login_validation_field.html("The fields can not be empty!")
            }
        })
    })
</script>

<body>

    {#    popping up messages        #}
        {% if messages %}
            {% for message in messages %}
                <div class="alert text-center alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %}

    <div id="box" style=" background-color:transparent;">

        <div id="main"></div>

        <div id="loginform">
            <h1>LOGIN</h1>
            <form id="js-login-form" action="{% url 'gym_website_app:signup & login' %}" method="post">
                {% csrf_token %}
                <input id="js-login-username" type="text" placeholder="Username" name="username" value="" /><br>
                <input id="js-login-password" type="password" placeholder="Password" name="password" value="" /><br>
                <input id="js-login-next" type="hidden" name="next" value="{{ request.GET.next }}"/>
                <p id="js-login-validation" style="color: red;font-size: 75%"></p>
                <button id="js-login-button" type="submit" name="submit" value="login">LOGIN</button>
            </form>
        </div>

        <div id="signupform">
            <h1>SIGN UP</h1>
            <form id="js-signup-form" action="{% url 'gym_website_app:signup & login' %}" method="post">
                {% csrf_token %}
                <input type="text" id="js-signup-username" placeholder="Full Name" name="username" value=""/><br>
                <p id="js-signup-username-validation" style="font-size:70%; font-family: 'Noto Sans Old Italic',serif"></p>
                <input type="email" id="js-signup-email" placeholder="Email" name="email" value=""/><br>
                <input type="password" id='js-signup-password' placeholder="Password" name="password" value=""/><br>
                <input type="password" id="js-signup-confirm-password" placeholder="Confirm Password"/><br>
                <p id="js-signup-con-pass-validation" style="font-size: 70%;font-family: 'Noto Sans Old Italic',serif;color: #8b1523"></p>
                <button id="js-signup-button" type="submit" name="submit" value="signup">SIGN UP</button>
            </form>
        </div>

        <div id="login_msg">Have an account?</div>
        <div id="signup_msg">Don't have an account?</div>

        <button id="login_btn">LOGIN</button>
        <button id="signup_btn">SIGN UP</button>


    </div>
</body>
</html>